### ISSUE TITLE
usability issues

### ISSUE THREAD

**Issue by gregcaporaso** [johnchase/cual-id#3]
I needed to generate some sample ids this morning and came across a few issues:

- [ ] README.md has the wrong script name (``BC_generator`` instead of ``Cual-ID``)
- [ ] Calling ``Cual-ID create-ids`` fails with traceback when called with no options - possible to just display the help text instead? Command line users shouldn't get a traceback. 
- [ ] help text for ``Cual-ID create-ids`` is confusing as the positional argument is required the ``[ ]`` imply that it's optional
- [ ] when specifying a prefix with ``-p``, the separator character that's used (``:``) is non MEINS-compliant, so keemei warns about it. Could this be replaced with a ``.``? 
- [ ] optionally write the ids to stdout - this is nice if you're populating a google spreadsheet with them (when maybe you don't end up using the file that's created, but just copy/pasting from it)

**Comment by johnchase** [comment]
This issue is closed as the interface has changed
