### ISSUE TITLE
Running validation of cual-ids when generated in batch

### ISSUE THREAD

**Issue by ebolyen** [johnchase/cual-id#9]
On the off chance that someone's system doesn't have a clock accurate to the chosen interval, we should create a running validator that compares every ID to its immediate predecessor for uniqueness between the two. 
Should failure of this condition raise on exception? or would it just retry until it succeeds, failing out after so many retries?

**Comment by johnchase** [comment]
@ebolyen I think it should just try until a valid ID is passed, or may try 10 times and then fail because something is wrong with the users clock. Were you thinking of using this in place of the time step or in addition to?
